#!/bin/bash

# Update code
cd $(dirname $(readlink -f -- $(readlink -f -- "$0")))
git pull

URL=$(cat /etc/check_mk/agent-updater.cfg | egrep '^URL=' | cut -d= -f2)
if [ "$URL" == "" ] ; then
  echo "agent-updater: no URL set in config file"
  exit 1
fi

installed_version=$(dpkg-query -W check-mk-agent | cut -d$'\t' -f2)
file=$(curl -s ${URL}/agents/ | egrep "^<li><a href" | sed 's/<li><a href="\(.*\)">.*$/\1/' | grep 'all.deb')
current_version=$(echo $file | cut -d_ -f2)
echo "check-mk-agent: installed={$installed_version}, current={$current_version}"

if [ "$installed_version" != "$current_version" ]; then
  curl -s -o/tmp/check-mk-agent.deb ${URL}/agents/${file}
  apt install /tmp/check-mk-agent.deb
  rm /tmp/check-mk-agent.deb
fi

for plugin in $(ls /usr/lib/check_mk_agent/plugins) ; do
  http_code=$(curl -s -v -o/tmp/checkmk-plugin ${URL}/agents/plugins/${plugin} 2>&1| grep '< HTTP/1.1 ' | cut -d' ' -f3)
  if [ "${http_code}" != "200" ]; then
    echo "plugin ${plugin}: error ${http_code}"
    continue
  fi
  diff -q /usr/lib/check_mk_agent/plugins/${plugin} /tmp/checkmk-plugin >/dev/null
  if [ "$?" == "1" ] ; then
    echo "plugin ${plugin}: new version"
    mv /tmp/checkmk-plugin /usr/lib/check_mk_agent/plugins/${plugin}
    chmod +x /usr/lib/check_mk_agent/plugins/${plugin}
  else
    echo "plugin ${plugin}: up-to-date"
  fi
done
