#!/bin/bash
. "$(dirname "$(readlink -f "$0")")/functions.sh"

VERSION=$(grep OMD_VERSION /opt/omd/sites/*/share/omd/omd.info | cut -d'=' -f2 | xargs)
VERSION=${VERSION%.cre}
LIST=`curl -s https://checkmk.com/de/download | grep "window.data =" | sed 's/^.*window.data = \(.*\);/\1/'`
# filter list for the newest production version
SUPPORTED_VERSIONS=$(echo $LIST | jq -r '.downloads.cmk.cre | keys | map(select(test("p"))) | reverse | join("\n")')

evaluate "" check-mk "${SUPPORTED_VERSIONS}" "${VERSION}"
