#!/bin/bash
DRUPAL_INSTALLS=`cat /etc/check_mk/drupal-version.cfg`
for i in $DRUPAL_INSTALLS ; do
  LATEST=`cd "$i"; composer show --latest --minor-only drupal/core 2>/dev/null | grep '^latest *:' | sed 's/^latest *: \([0-9.]\+\)$/\1/' | xargs`
  VERSION=`cd "$i"; vendor/bin/drush status | egrep "^Drupal version *:" | sed 's/^.*: \([0-9.]\+\)/\1/' | xargs`

  if [ "${VERSION}" = "${LATEST}" ] ; then
    echo "0 \"Drupal version ${i}\" - Current version: ${VERSION}"
  else
    echo "1 \"Drupal version ${i}\" - Current version: ${VERSION}, available: ${LATEST}"
  fi
done
