#!/bin/bash
. "$(dirname "$(readlink -f "$0")")/functions.sh"

DRUPAL_INSTALLS=`cat /etc/check_mk/drupal-version.cfg`
ALL_SUPPORTED=$(get_supported_endoflife "drupal")

for i in $DRUPAL_INSTALLS ; do
  VERSION=`cd "$i"; vendor/bin/drush status | egrep "^Drupal version *:" | sed 's/^.*: \([0-9.]\+\)/\1/' | xargs`

  evaluate "${i}" Drupal "${ALL_SUPPORTED}" "${VERSION}"
done
