#!/bin/bash
. "$(dirname "$(readlink -f "$0")")/functions.sh"

INSTALLS=`cat /etc/check_mk/matomo-version.cfg`

ALL_SUPPORTED=$(get_supported_endoflife "matomo")

for I in $INSTALLS ; do
  VERSION=$(grep "const VERSION = '" "${I}/core/Version.php" | sed "s/^.*'\([0-9.]*\)';/\1/" | xargs)

  evaluate "${I}" Matomo "${ALL_SUPPORTED}" "${VERSION}"
done
