#!/bin/bash
. "$(dirname "$(readlink -f "$0")")/functions.sh"

INSTALLS=`cat /etc/check_mk/mediawiki-version.cfg`

ALL_SUPPORTED=`curl -s https://www.mediawiki.org/wiki/Download | egrep '"https://releases.wikimedia.org/mediawiki/[0-9.]*/mediawiki-[0-9.]*\.zip\"' | sed "s/^.*mediawiki-\([0-9.]*\)\.zip.*$/\1/"`
LATEST=$(echo "${ALL_SUPPORTED}" | head -n1 | xargs)

for I in $INSTALLS ; do
  VERSION=`grep "'MW_VERSION'" "${I}/includes/Defines.php" | sed "s/^.*'\([0-9.]*\)' );/\1/" | xargs`

  evaluate "${I}" Mediawiki "${ALL_SUPPORTED}" "${VERSION}"
done
