#!/bin/bash
. "$(dirname "$(readlink -f "$0")")/functions.sh"

INSTALLS=`cat /etc/check_mk/nextcloud-version.cfg`

ALL_SUPPORTED=$(curl -s https://raw.githubusercontent.com/wiki/nextcloud/server/Maintenance-and-Release-Schedule.md | head -n 20 | cut -d'|' -f6 | egrep '\*\*([0-9.]+)\*\*' | cut -d'*' -f3)
LATEST=$(echo "${ALL_SUPPORTED}" | head -n1 | xargs)

for i in $INSTALLS ; do
  VERSION=`grep "OC_VersionString =" "${i}/version.php" | sed "s/^.*= '\(.*\)';/\1/" | xargs`

  evaluate "${i}" Nextcloud "${ALL_SUPPORTED}" "${VERSION}"
done
