#!/bin/bash
INSTALLS=`cat /etc/check_mk/rainloop-version.cfg`
for i in $INSTALLS ; do
  LATEST=$(curl -s https://www.rainloop.net/try-now/ | grep '"subline"' | cut -d\> -f2 | cut -d\< -f1 | cut -b2-)
  VERSION=$(grep "define('APP_VERSION'" "${i}/index.php" | cut -d\' -f4)

  if [ "${VERSION}" = "${LATEST}" ] ; then
    echo "0 \"Rainloop version ${i}\" - Current version: ${VERSION}"
  else
    echo "1 \"Rainloop version ${i}\" - Current version: ${VERSION}, available: ${LATEST}"
  fi
done
