#!/bin/bash
. "$(dirname "$(readlink -f "$0")")/functions.sh"

LATEST=$(curl -s https://roundcube.net/download/ | grep "Stable version - " | cut -d- -f2 | cut -d\< -f1 | cut -b2- | xargs)

INSTALLS=`cat /etc/check_mk/roundcube-version.cfg`
for i in $INSTALLS ; do
  VERSION=$(grep "define('RCUBE_VERSION'" "${i}/program/lib/Roundcube/bootstrap.php" | cut -d\' -f4)

  evaluate "${i}" Roundcube "${LATEST}" "${VERSION}"
done
