#!/bin/bash
INSTALLS=`cat /etc/check_mk/roundcube-version.cfg`
for i in $INSTALLS ; do
  LATEST=$(curl -s https://roundcube.net/download/ | grep "Stable version - " | cut -d- -f2 | cut -d\< -f1 | cut -b2-)
  VERSION=$(grep "define('RCUBE_VERSION'" "${i}/program/lib/Roundcube/bootstrap.php" | cut -d\' -f4)

  if [ "${VERSION}" = "${LATEST}" ] ; then
    echo "0 \"Roundcube version ${i}\" - Current version: ${VERSION}"
  else
    echo "1 \"Roundcube version ${i}\" - Current version: ${VERSION}, available: ${LATEST}"
  fi
done
